#' Extract information from a credentials file
#'
#' Extract information from a \code{credetials.yaml} so as to access a database.
#' This will generally used in conjunction with \code{credentials_connect}
#' The list generated by \code{credentials_extract} is passed as the \code{options_list} argument of \code{credentials_connect}).

#' @param credentials_path The path to a credentials file through which
#' the database connection will be established.
#' If \code{NULL} the function will attempt to find an \code{credentials.yaml}
#' upwards in the directory tree
#' @param credentials_folder Whether to search for a \code{credentials} folder (the
#' default behvior); only applicable if \code{credentials_path} is \code{NULL}.
#' @param credentials_file The name of the file (not including the path, unless
#'  \code{all_in_file} is set to \code{TRUE}) with
#' your environment setting. Normally, this should be \code{credentials.yaml}. If an explicit \code{credentials_path} is provided, this
#'  argument is ignored. Otherwise, the \code{credentials_file} will be
#'   searched for, with the expectation that it is in a directory
#'    named \code{credentials}.
#' @param credentials_search_limit The number of directories upwards to search for a \code{credentials/credentials.yaml} file; only relevant if \code{credentials_path = NULL}
#' default is \code{FALSE}
#' @param all_in_file Whether to disregard the \code{credentials_path} argument entirely.
#' If set to \code{TRUE}, the \code{credentials_file} argument should be the
#' entire pathway to the credentials file in question (ie, path and file name)
#' combined.
#' If set to \code{TRUE}, the function will use the
#' @return A list of PostgreSQL-related options obtained from the
#' environment file, meant to be passed  to \code{credentials_connect}.
#' @import dplyr
#' @import yaml
#' @import httr
#' @export

credentials_extract <- function(credentials_path = NULL,
                                credentials_folder = TRUE,
                                credentials_file = 'credentials.yaml',
                                credentials_search_limit = 10,
                                all_in_file = FALSE){


  if(all_in_file){
    credentials_path <- credentials_file
  } else {
    # If no yaml file, set to the standard
    if(is.null(credentials_file)){
      credentials_file <- 'credentials.yaml'
    }

    # If no path to the credentials.yaml is explicitly provided,
    # try to find one by searching the directory structure upwards
    if(is.null(credentials_path)){

      # Define starting point
      this_dir <- getwd()

      # Test to see if it's there
      credentials_in_dir <- credentials_file %in% dir(paste0(this_dir, ifelse(credentials_folder,
                                                                              '/credentials',
                                                                              '')))

      # Helper functon for chopping down directory (ie, going up a level)
      chop_dir <- function(x){
        x_split <- unlist(strsplit(x, '/'))
        # take off last element
        x_split <- x_split[1:(length(x_split)-1)]
        # Return the reformed
        paste0(x_split, collapse = '/')
      }

      # Counter to ensure we don't search too far upwards
      credentials_search_counter <- 0
      while(!credentials_in_dir & credentials_search_counter <= credentials_search_limit){
        # Move up one
        this_dir <- chop_dir(this_dir)
        # See if it's in there
        credentials_in_dir <- credentials_file %in% dir(paste0(this_dir,
                                                               ifelse(credentials_folder,
                                                                      '/credentials',
                                                                      '')))
        credentials_search_counter <- credentials_search_counter +1
      }
      credentials_path <- paste0(this_dir, paste0(ifelse(credentials_folder,
                                                         '/credentials/',
                                                         '/'),
                                                  credentials_file))
    } else {
      # A yaml path was manually supplied - combine to yaml file
      credentials_path <- paste0(credentials_path, '/', credentials_file)
      # Remove any double parentheses (may not be applicable)
      credentials_path <- gsub('//', '/', credentials_path)
    }

    message(paste0('Using credentials at ', credentials_path))
    # If no yaml was identified after the search limit was maxed, return error
    good_to_go <- file.exists(credentials_path) & !dir.exists(credentials_path)
    if(!good_to_go){
      credentials_path <- NULL
    }
    if(is.null(credentials_path)){
      stop(paste0('No credentials file could be find. Ensure you have one.'))
    }
  }

  # Read in yaml file and create list object
  credentials <- yaml.load_file(credentials_path)
  return(credentials)
}

